services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: supcontent-api
    restart: always
    environment:
      PORT: 1234
      DATABASE_URL: postgres://supcontent:supcontent@db:5432/supcontent
      REDIS_URL: redis://redis:6379
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    depends_on:
      - db
      - redis
    ports:
      - "1234:1234"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: supcontent-web
    restart: always
    depends_on:
      - api
    ports:
      - "4173:80"

  db:
    image: postgres:15
    container_name: supcontent-db
    restart: always
    environment:
      POSTGRES_USER: supcontent
      POSTGRES_PASSWORD: supcontent
      POSTGRES_DB: supcontent
    ports:
      - "5432:5432"
    volumes:
      - supcontent_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: supcontent-redis
    restart: always
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: supcontent-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  supcontent_pgdata:
